config/routes.rb
BwUpload::Application.routes.draw do

  get '/missing' => 'bw_files#missing', :as => 'missing'
  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'my-account' => 'users#my_account', :as => 'my_account'
  get 'downloads/:permalink' => 'bw_files#download', :as => 'download'
  resources :users
  resources :sessions
  resources :bw_files, path: 'bw-files'

  get '/files' => 'bw_files#index'
  get '/admin' => 'home#admin', :as => 'admin'
  match '/admin-create' => 'bw_files#admin_create', :as => 'admin_create', via: [:get, :post]
 
  root to: 'home#index'
end

app/models/bw_attachment.rb
class BwAttachment < ActiveRecord::Base  
  belongs_to :bw_file  
  has_attached_file :binary_file
  validates_attachment :binary_file,    
    presence: true
end

app/models/bw_file.rb
class BwFile < ActiveRecord::Base
  attr_accessor :email_ids

  has_many :bw_attachments 
  accepts_nested_attributes_for :bw_attachments

  validates :email_ids, :presence => { :message => "You should send the file to at least one person." }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :bw_files  
  attr_accessor :password
  
  before_save :encrypt_password  

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates :password, :length => {:minimum => 6}, :on => :create

  validates :email, :presence => true, :uniqueness => true

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def admin?
    if admin == true
      return true
    else
      return false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def flash_to_headers
    if request.xhr?
      #avoiding XSS injections via flash
      flash_json = Hash[flash.map{|k,v| [k,ERB::Util.h(v)] }].to_json
      response.headers['X-Flash-Messages'] = flash_json
      flash.discard
    end
  end

  helper_method :current_user

  def require_user
    if current_user.blank?
      redirect_to root_path, :notice => "You must log in"
    end
  end

  def require_admin
    if current_user.blank? || current_user.admin? == false
      flash[:errors] = "You are not authorized. This incident will be reported."
      redirect_to root_path
    end
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate    
    authenticate_or_request_with_http_basic do |username, password|
      username == "boondock" && password == "3635Walker"
    end    
  end
end

app/controllers/bw_files_controller.rb
class BwFilesController < ApplicationController
  before_filter :authenticate, :only => %w{admin_create index}

  def index
    @files = BwFile.order('id DESC')
  end

  def create
    @bw_file = BwFile.new(bw_file_params)
    if @bw_file.save      
      email = find_email
      Notifier.send_file(@bw_file, email).deliver
      redirect_to root_path, notice: "File sent"
    else
      flash[:errors] =  "something went wrong"
      render 'home/index'
    end
  end

  def admin_create
    @bw_file = BwFile.new(bw_file_params)
    if @bw_file.save      
      Notifier.send_file(@bw_file, @bw_file.receiver_email).deliver
      redirect_to admin_path, :notice => "File sent"
    else
      flash[:errors] =  "something went wrong"
      render 'home/admin'
    end
  end

  def destroy  
    bw_file = BwFile.find params[:id]
    bw_file.bw_attachments.each { |a| a.destroy }    
    bw_file.destroy
    redirect_to '/admin'
  end

  def find_email
    email = []
    if params[:bw_file][:email_ids]
      email << 'cnagy@boondockwalker.com' if params[:bw_file][:email_ids].include?('1')
      email << 'mnead@boondockwalker.com' if params[:bw_file][:email_ids].include?('2')
      email << 'bwillse@boondockwalker.com' if params[:bw_file][:email_ids].include?('3')
      email << 'dchristopher@boondockwalker.com' if params[:bw_file][:email_ids].include?('4')
      email << 'stipton@boondockwalker.com' if params[:bw_file][:email_ids].include?('5')
      email << 'dhafer@boondockwalker.com' if params[:bw_file][:email_ids].include?('6')
      email << 'tbrennan@boondockwalker.com' if params[:bw_file][:email_ids].include?('7')
    end
    email.join(', ')
  end 

  def bw_file_params
    params.require(:bw_file).permit(:name, :receiver_email, bw_attachments_attributes: [:id, :binary_file, :_destroy], email_ids: [])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate, :only => %w{admin}
  after_action :allow_iframe

  def index
    @bw_file = BwFile.new
    @bw_file.bw_attachments.build
  end

  def admin
    @bw_file = BwFile.new
    @bw_file.bw_attachments.build
    @files = BwFile.order('id DESC')
  end

  private

  def allow_iframe
    response.headers['X-Frame-Options'] = 'ALLOW-FROM http://bw.boondockwalkerstaging.com'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    reset_session
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to my_account_path, :notice => "Logged in!"
    else
      flash[:error] = "Invalid email or password"
      redirect_to login_path
    end
  end

  def destroy
    reset_session
    session[:user_id] = nil
    redirect_to root_path, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_admin, except: %w{my_account create}
  before_filter :require_user, only: %w{my_account}

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def my_account
    @bw_file = BwFile.new
    @sent_files = BwFile.where user_id: current_user.id
  end

  def create
    @user = User.new params[:user]
    if @user.save
      session[:user_id] = @user.id
      redirect_to my_account_path, :notice => "Welcome to BW Send!"
    else
      render 'new'
    end
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    if @user.update_attributes params[:user]
      redirect_to users_path, :notice => "Updated user"
    else
      render "edit"
    end
  end

  def destroy
    user = User.find params[:id]
    user.destroy
    user.save
    redirect_to users_path, :notice => "Deleted user."    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper  
end

app/helpers/bw_files_helper.rb
module BwFilesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bw_files/index.html.erb
<br />
<br />
  <% @files.each do |bw_file| %>
    <table border="0" cellpadding="10" cellspacing="0" width="100%">
      <tbody>
        <tr style="border: 1px solid #DDD;">
          <th scope="col" valign="top" width="25%" style="background-color: #D8E2EA; color: #369; font-family: Helvetica; font-size: 14px; font-weight: bold; line-height: 150%; text-align: left;border: 1px solid #DDD;border-right: none;">
            DATE
          </th>
          <th scope="col" valign="top" width="50%" style="background-color: #D8E2EA; color: #369; font-family: Helvetica; font-size: 14px; font-weight: bold; line-height: 150%; text-align: left;border: 1px solid #DDD;border-left: none;">
            FILE NAME
          </th>
          <th style="background-color: #D8E2EA; color: red; font-family: Helvetica; font-size: 14px; font-weight: bold; line-height: 150%; text-align: right;padding-right: 8px;border: 1px solid #DDD;border-left: none;">
            <%= link_to "Delete", bw_file_path(bw_file), method: 'delete', data: {confirm: "Are you sure?"}, style: 'color:red' %>
          </th>
        </tr>
        <% bw_file.bw_attachments.each do |attachment| %>
        <tr style="border: 1px solid #DDD;font-weight: bold;" style="background: <%= cycle("#EEEEEE", "#EFEFEF") %>">
          <td valign="top" style="border: 1px solid #DDD;border-top: none;border-right: none;">
            <%= attachment.created_at.strftime("%b %d, %Y") %>
          </td>
          <td valign="top" style="border-bottom: 1px solid #DDD;border-right: none;">
            <%= attachment.binary_file.original_filename %>
          </td>
          <td style="border-bottom: 1px solid #DDD;border-right: 1px solid #DDD;">
            <a href="<%= attachment.binary_file.url %>" target="_blank" style="    color: #369; font-family: Arial; font-size: 15px; font-weight: bold; letter-spacing: -.5px; line-height: 100%; text-align: center;    padding: 4px 12px; text-decoration: underline;">
              Download
            </a>
            <%= attachment.binary_file_file_size.to(:mb) %>
          </td>
        </tr>
      <% end %>
  </tbody>
</table>
<% end %>

app/views/bw_files/missing.html.erb
<style>
.errorExplanation h2 {display:none;}
</style>

  <div class="row">
    <br>    
    <div class="twelve columns">
      <div class="row">
      </div>
    </div>
  </div>
 
 <br>
 <br>
 
  <div class="row">
    <div class="twelve columns">
      <div class="row">
 
    <!-- Content -->
 
        <div class="eight columns centered">
          <div class="panel radius">
            <div class="row">
              <div class="row">
                <div class="nine columns centered">
                  <div class="row collapse">
                    <span class="main-listing">
                    <h2 style="text-align: centered;">Uh-oh!</h2>
                    <p class="lead">it appears that file is no longer available :(</p>
                    <hr />
                    
                    <p class="lead"><a class="button nice radius small" href="/">go to homepage</a></p>
                </div>
              </div>
              <div class="row">
                <div class="nine columns centered">
                  <div class="row collapse">
                    <div class="two mobile-one columns">
                    </div>
                    <div class="ten mobile-three columns">
                    </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="nine columns centered">
                  <div class="row collapse">
                    <div class="twelve columns centered">
                    </div>
                  </div>
                </div>
              <br>
              <div class="row">
                <div class="nine columns centered">
                  <div class="row collapse">
                    <div class="two mobile-one columns">
                    </div>
                    <div class="ten mobile-three columns">
                      <br>
                    </div>
                  </div>
                </div>
              </div>
                <br>
                <br>
            </div>
          </div>
        </div>
 
    <!-- End Content -->
 
      </div>

app/views/home/_bw_attachment_fields.html.erb
<%= f.fields_for :bw_attachments, :wrapper => false do |attachment| %>  
  <div class="row collapse fields fadeIn">
    <div class="small-3 large-2 columns">
      <span class="prefix"><i class='fi-paperclip'></i></span>
    </div>
    <div class="small-6 large-7 columns">
      <%= attachment.file_field :binary_file, required:'' %>
      <br>
    </div>
    <div class="large-3 small-3 columns text-center">
      <%= attachment.link_to_remove "×", class: 'alert tiny button radius' %>
    </div>
  </div>
<% end %>
<%= f.link_to_add 'Add another file', :bw_attachments, class: 'success button radius tiny' %>

app/views/home/admin.html.erb
<br />
<!-- Content -->
<div id="myModal" class="small" style='display:none; background: white;padding-top: 38px;'>
  <span class="main-listing">
    <h2 style="text-align: large-centered;">Please be patient</h2>
    <p class="lead">upload time depends on your connection</p>
  </span>
  <h2 style="text-align:center; background: white;z-index:999;">uploading files...</h2>
  <p class='text-center'><progress id='p' value='1' max='1000' style='width:60%'><span>0</span>%</progress></p>
  <br />
</div>

<%= nested_form_for @bw_file, url: admin_create_path, html: { multipart: true, class: 'fadeIn' } do |f| %> 
  <%= hidden_field_tag "bw_file[email_ids][]", 6 %>         
  <div class="row">
    <span class="main-listing">
      <h2 style="text-align: large-centered;">Send someone a file</h2>
      <p class="lead">by choosing your recipients</p>
    </span>
    <hr />        
    <div class="large-12 columns">                      
    </div>
  </div>
  
  <div class="row">
    <div class="large-5 columns">
      <h4 class='subheader'>1. Attach Files</h4>
      <div id='attachments'>
        <%= render partial: 'home/bw_attachment_fields', locals: {f: f} %>
      </div>
    </div>
    <div class="large-5 columns end">
      <h4 class='subheader'>2. Choose Recipients</h4>
      <%= f.error_messages %>
      <%= f.text_field :receiver_email, class: 'input-text radius required', placeholder: 'one@example.com, two@example.com...' %>
      <%= f.text_area :name, class: 'input-text radius', rows: 5, placeholder: 'You can provide notes or instructions here.' %>        
      <%= submit_tag "Send", id: 'upload-button', class: 'button radius expand' %>
    </div>
  </div>  
<% end %>
    
  <hr />
  <h4 class='subheader'>Previous File Uploads</h4>

  <% @files.each_with_index do |bw_file, index| %>
    <table border="0" cellpadding="10" cellspacing="0" width="100%" class='<%= "hide" if index > 0 %>'>
      <tbody>
        <tr style="">
          <th scope="col" valign="top" width="25%" style="font-family: Helvetica; font-size: 14px; font-weight: bold; line-height: 150%; text-align: left;border: 1px solid #CCC;border-right: none;">
            DATE
          </th>
          <th scope="col" valign="top" width="50%" style="font-family: Helvetica; font-size: 14px; font-weight: bold; line-height: 150%; text-align: left;border: 1px solid #CCC;border-left: none;border-right:none">
            FILE NAME
          </th>
          <th style="color: red; font-family: Helvetica; font-size: 14px; font-weight: bold; line-height: 150%; text-align: right;padding-right: 8px;border: 1px solid #CCC;border-left: none;">
            <%= link_to "Delete", bw_file_path(bw_file), method: 'delete', data: {confirm: "Are you sure?"}, class: 'tiny alert label radius' %>
          </th>
        </tr>
        <% bw_file.bw_attachments.each do |attachment| %>
          <tr style="border: 1px solid #CCC;font-weight: bold;" style="background: <%= cycle("#EEEEEE", "#EFEFEF") %>">
            <td valign="top" style="border: 1px solid #CCC;border-top: none;border-right: none;">
              <%= attachment.created_at.strftime("%b %d, %Y") %>
            </td>
            <td valign="top" style="border-bottom: 1px solid #CCC;border-right: none;">
              <%= attachment.binary_file.original_filename %>
            </td>
            <td style="border-bottom: 1px solid #CCC;border-right: 1px solid #CCC;">
              <a href="<%= attachment.binary_file.url %>" target="_blank" style="    color: #369; font-family: Arial; font-size: 15px; font-weight: bold; letter-spacing: -.5px; line-height: 100%; text-align: center;    padding: 4px 12px; text-decoration: underline;">
                Download
              </a>
              <%= attachment.binary_file_file_size.to(:mb) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>

<div class='large-12 columns text-center'>
  <a href='#' class='see-more text-center tiny center blue button radius'>See more files</a>
</div>

<!-- End Content -->
<% content_for :ready do %>
$('#upload-button').on('click', function(e){
  if ($('.fields:visible input[type="file"]').val() && $('#bw_file_receiver_email').val() ) {
    $('#myModal').show();
    $('#myModal').next('form').hide();    
    fakeUpload();
  }
});
<% end %>

app/views/home/index.html.erb
<br />
<br />
<br />
<!-- Content -->
<div id="myModal" class="small" style='display:none; background: white;padding-top: 38px;'>
  <span class="main-listing">
    <h2 style="text-align: large-centered;">Please be patient</h2>
    <p class="lead">upload time depends on your connection</p>
  </span>
  <h2 style="text-align:center; background: white;z-index:999;">uploading files...</h2>
  <p class='text-center'><progress id='p' value='1' max='1000' style='width:60%'><span>0</span>%</progress></p>
</div>

<%= nested_form_for @bw_file, url: bw_files_path, html: { multipart: true, class: 'fadeIn' } do |f| %>          
  <div class="row">                
    <%= f.error_messages %>
    <div class="large-4 columns">
      <h4 class='subheader'>1. Attach Files</h4>
      <%= render partial: 'home/bw_attachment_fields', locals: {f: f} %>      
    </div>
    <div class="large-4 columns">       
      <h4 class='subheader'>2. Select Recipients</h4>
      <label for="bw_file[email_ids][]" class="error-message alert button tiny radius expand" style='display:none'>You must select at least one email.</label>               
      <label class="radius email-input"><i class='fi-mail'><%= check_box_tag "bw_file[email_ids][]", 2, nil, :class => 'email' %> <p>Mark Nead</p></i></label>
      <label class="radius email-input"><i class='fi-mail'><%= check_box_tag "bw_file[email_ids][]", 3, nil, :class => 'email' %> <p>Brian Willse</p></i></label>
      <label class="radius email-input"><i class='fi-mail'><%= check_box_tag "bw_file[email_ids][]", 7, nil, :class => 'email' %> <p>Tim Brennan</p></i></label>
      <label class="radius email-input"><i class='fi-mail'><%= check_box_tag "bw_file[email_ids][]", 5, nil, :class => 'email' %> <p>Seth Tipton</p></i></label>
      <label class="radius email-input"><i class='fi-mail'><%= check_box_tag "bw_file[email_ids][]", 6, nil, :class => 'email' %> <p>Dillon Hafer</p></i></label>
    </div>
    <div class='large-4 columns'>
      <h4 class='subheader'>3. Add Notes <small>(optional)</small></h4>
      <%= f.text_area :name, class: ' radius', rows: 5, placeholder: 'You can provide notes or instructions here.' %>
      <%= submit_tag "Send", id: 'upload-button', class: 'orange button radius expand' %>
    </div>
  </div>
  <div class='row'>
    <div class='large-12 columns'>
    </div>
  </div>
<% end %>
  
<!-- End Content -->
    
<% content_for :ready do %>
  $('input[type="checkbox"]').on('change', function(){
    $(this).parent().toggleClass('fi-mail').toggleClass('fi-check')
    $(this).parent().parent().toggleClass('is_green');
  })

  $('.email').on('change', function() {
    if ($('.email:checkbox:checked').length == 0) {
      $('.error-message').show();
      $('label.email-input').addClass('checkbox-error');
      $('label.email-input i.general').removeClass('fi-mail').addClass('fi-remove').addClass('red')
    } else {
      $('label[for="bw_file[email_ids][]"].error-message').hide();
      $('label.email-input').removeClass('checkbox-error');
      $('label.email-input i.general').addClass('fi-mail').removeClass('fi-remove').removeClass('red')
      $('label.email-input .email:checkbox:checked').parent().removeClass('fi-mail').addClass('fi-check').parent().addClass('is_green')
    }
  });

  $('#upload-button').on('click', function(e){
    if ($('.fields:visible input[type="file"]').val() && $('.email:checkbox:checked').length > 0) {
      $('#myModal').show();
      $('#myModal').next('form').hide();
      fakeUpload();   
    } else if ($('.email:checkbox:checked').length == 0) {
      $('.error-message').show();
      $('label.email-input').addClass('checkbox-error');
      $('label.email-input i.general').removeClass('fi-mail').addClass('fi-remove').addClass('red')
      e.preventDefault();
    }
  });
<% end %>       

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title><%= content_for?(:title) ? yield(:title) : "BW Send" %></title>  
    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no, width=device-width" />        
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <link href="//fonts.googleapis.com/css?family=Nobile" rel="stylesheet" type="text/css">  
    <!-- Set the viewport width to device width for mobile -->
    <%= stylesheet_link_tag "application" %>    
    <%= javascript_include_tag "vendor/modernizr" %>    
    <%= csrf_meta_tags %>
  </head>
  <body>      
    <% if flash[:error] %>
      <div class='alert-box error'><%= flash[:error] %></div>
    <% end %>
   
     <div class="row">
        <div class="large-12 columns">
          <% if flash[:notice] %>
            <div data-alert class="alert-box success radius">
              <%= flash[:notice] %>
              <a href="#" class="close">&times;</a>
            </div>
          <% end %>
           <%= yield %>
       </div>
     </div>
 
    <!-- Footer -->
    <%= javascript_include_tag "application" %>    
    <script><%= yield(:ready) %></script>
  </body>
</html>

app/views/notifier/clean_up_email.html.erb
Files that were removed.
<ul>
  <% @files[:files].each do |f| %>
    <li><%= f[0] %></li>
  <% end %>
</ul>

app/views/users/edit.html.erb
<h4>Edit User</h4>
<hr />
<%= form_for @user, :html => {:class => "nice"} do |f| %>
  <%= f.error_messages %>
  <%= field_set_tag do %>
  <h4>User: <%= @user.email %></h4>

  <%= f.label :email, "Username" %>
  <%= f.text_field :email, :class => "input-text" %>

  <span class='label radius'>Leave password fields blank if you don't want to change the password</span>
  <%= f.label :password %>
  <%= f.password_field :password, :class => "input-text" %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, :class => "input-text" %>

  <%= f.label :admin do %>
    <%= f.check_box :admin %>Admin?
  <% end %>

  <%= f.submit "Update User", :class => "yellow button nice radius" %>
  <br /><br />
  <% end %>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/my_account.html.erb
<h1>Your Account</h1>
<hr />
<div class='row'>
  <div class='two columns centered'>
    <%= link_to "Send File", 'javascript:void(0)', data: {reveal_id: 'send_file'}, class: 'large button radius success' %>
  </div>
</div>

<br>
<br>
<div class='row'>
  <div class='twelve columns'>
    <div class='panel'>
      <h3>Your files</h3>
      <dl class="tabs">
        <dd class="active"><a href="#sent">Sent</a></dd>
        <dd><a href="#received">Received</a></dd>
      </dl>
      <ul class="tabs-content">
        <li class="active" id="sentTab">
          <table class='file-table'>
            <thead>
              <tr>
                <th>File Name</th><th>Receiver</th><th>Date Uploaded</th><th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @sent_files.each do |file| %>
              <tr>
                <td><%= file.binary_file.original_file_name %><i class='general foundicon-mic'></i> <%= link_to 'Music.mp3', 'javascript:void(0)' %></td><td>mailer@boondockwalker.com</td><td><%= Date.today %></td><td><i class='general foundicon-trash'></i> <i class='general foundicon-inbox'></i></td>
              </tr>
              <% end %>
              <tr>
                <td><i class='general foundicon-photo'></i> <%= link_to 'Photo.png', 'javascript:void(0)' %></td><td>mailer@boondockwalker.com</td><td><%= Date.today %></td><td><i class='general foundicon-trash'></i> <i class='general foundicon-inbox'></i></td>
              </tr>
              <tr>
                <td><i class='general foundicon-video'></i> <%= link_to 'Video.mp4', 'javascript:void(0)' %></td><td>mailer@boondockwalker.com</td><td><%= Date.today %></td><td><i class='general foundicon-trash'></i> <i class='general foundicon-inbox'></i></td>
              </tr>
              <tr>
                <td><i class='general foundicon-page'></i> <%= link_to 'Document.pdf', 'javascript:void(0)' %></td><td>mailer@boondockwalker.com</td><td><%= Date.today %></td><td><i class='general foundicon-trash'></i> <i class='general foundicon-inbox'></i></td>
              </tr>                            
              <tr>
                <td><i class='general foundicon-paper-clip'></i> <%= link_to 'Other.app', 'javascript:void(0)' %></td><td>mailer@boondockwalker.com</td><td><%= Date.today %></td><td><%= link_to root_path do; "<i class='red general foundicon-trash'></i>".html_safe; end  %> <i class='general foundicon-inbox'></i></td>
              </tr>                            
            </tbody>
          </table>
        </li>
        <li id="receivedTab">
          <table class='file-table'>
            <thead>
              <tr>
                <th>File Name</th><th>Date Uploaded</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Bar.mp3</td><td><%= Date.yesterday %></td>
              </tr>
            </tbody>
          </table>
        </li>
      </ul>
    </div>
  </div>
</div>

<% content_for :reveal_modal do %>
<div id="send_file" class="reveal-modal [expand, xlarge, large, medium, small]">
  <h2>Send file!</h2>
  <p class="lead">just choose a file</p>
  <%= form_for @bw_file, :url => bw_files_path, :html => { :multipart => true } do |f| %>
  <div class="row">
    <div class="twelve columns" style='padding:0;'>
      <div class="row collapse">
        <div class="two mobile-one columns">
          <span class="prefix"><i class='general foundicon-mail'></i></span>
        </div>
        <div class="ten mobile-three columns">
          <%= f.email_field :receiver_email, placeholder: 'email@example.com' %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="twelve columns" style='padding:0;'>
      <div class="row collapse">
        <div class="two mobile-one columns">
          <span class="prefix"><i class='general foundicon-paper-clip'></i></span>
        </div>
        <div class="ten mobile-three columns">
          <%= f.file_field :binary_file, class: 'input-text radius' %>
        </div>
      </div>
    </div>
  </div>
    <%= submit_tag "Send", class: 'blue button nice radius full-width' %>
    <br>
    <br>
    <%= link_to "Cancel", 'javascript:void($("a.close-reveal-modal").click())', class: 'alert button nice radius full-width' %>
  <% end %>
  <a class="close-reveal-modal">&#215;</a>
</div>
<% end %>

app/views/users/new.html.erb
<h4>Add a new user</h4>
<hr />
<%= form_for @user, :html => {:class => "nice"} do |f| %>
<%= field_set_tag do %>
<%= f.error_messages %>
<%= f.label :email, "Username" %>
<%= f.text_field :email, :placeholder => "Username", :class => "input-text" %>

<%= f.label :password %>
<%= f.password_field :password, :placeholder => "••••••", :class => "input-text" %>

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation, :placeholder => "••••••", :class => "input-text" %>

<%= f.label :admin do %>  
  <%= f.check_box :admin %>Make user an admin?
<% end %>

<%= f.submit "Create User", :class => "yellow button nice radius" %>
<br /><br />
<% end %>
<% end %>